### PR TITLE
Axonaraw

### PR DESCRIPTION
**Pull request by sbuergers**
Depends on:

- [x] https://github.com/catalystneuro/nwb-conversion-tools/pull/166

Added a `HussainiRawNWBConverter` for converting .bin and .set data from Axona to NWB.

### CODE REVIEW

**Comment by CodyCBakerPhD** [comment]
PR #166 was merged - is this code working for you?

**Comment by sbuergers** [comment]
@CodyCBakerPhD yes, I can use it to convert to NWB. Though I have not tried lots of different test cases.  I also noticed that a manual validation of metadata vs metadata_schema using the `HussainiNWBConverter` still fails. Since this is not checked though it converts. See the error below:

```
ValidationError: Additional properties are not allowed ('ElectricalSeries' was unexpected)

Failed validating 'additionalProperties' in schema['properties']['Ecephys']:
    {'additionalProperties': False,
     'properties': {'Device': {'default': [{'description': 'Axona DacqUSB, '
                                                           'sw_version=1.2.2.16',
                                            'manufacturer': 'Axona',
                                            'name': 'Axona'}],
                               'items': {'$ref': '#/properties/Ecephys/properties/definitions/Device'},
                               'minItems': 1,
                               'type': 'array'},
                    'ElectrodeGroup': {'default': [{'description': 'Group '
                                                                   '0 '
                                                                   'electrodes.',
                                                    'device': 'Axona',
                                                    'location': '',
                                                    'name': 'Group0'},
                                                   {'description': 'Group '
                                                                   '1 '
                                                                   'electrodes.',
                                                    'device': 'Axona',
                                                    'location': '',
                                                    'name': 'Group1'},
                                                   {'description': 'Group '
                                                                   '2 '
                                                                   'electrodes.',
                                                    'device': 'Axona',
                                                    'location': '',
                                                    'name': 'Group2'},
                                                   {'description': 'Group '
                                                                   '3 '
                                                                   'electrodes.',
                                                    'device': 'Axona',
                                                    'location': '',
                                                    'name': 'Group3'}],
                                       'items': {'$ref': '#/properties/Ecephys/properties/definitions/ElectrodeGroup'},
                                       'minItems': 1,
                                       'type': 'array'},
                    'Electrodes': {'default': [{'data': ['Group0',
                                                         'Group0',
                                                         'Group0',
                                                         'Group0',
                                                         'Group1',
                                                         'Group1',
                                                         'Group1',
                                                         'Group1',
                                                         'Group2',
                                                         'Group2',
                                                         'Group2',
                                                         'Group2',
                                                         'Group3',
                                                         'Group3',
                                                         'Group3',
                                                         'Group3'],
                                                'description': 'The name '
                                                               'of the '
                                                               'ElectrodeGroup '
                                                               'this '
                                                               'electrode\n'
                                                               '                                '
                                                               'is a part '
                                                               'of.',
                                                'name': 'group_name'}],
                                   'items': {'$ref': '#/properties/Ecephys/properties/definitions/Electrodes'},
                                   'minItems': 0,
                                   'renderForm': False,
                                   'type': 'array'},
                    'definitions': {'Device': {'additionalProperties': False,
                                               'properties': {'description': {'description': 'Description '
                                                                                             'of '
                                                                                             'the '
                                                                                             'device '
                                                                                             '(e.g., '
                                                                                             'model, '
                                                                                             'firmware '
                                                                                             'version, '
                                                                                             'processing '
                                                                                             'software '
                                                                                             'version, '
                                                                                             'etc.)',
                                                                              'type': 'string'},
                                                              'manufacturer': {'description': 'the '
                                                                                              'name '
                                                                                              'of '
                                                                                              'the '
                                                                                              'manufacturer '
                                                                                              'of '
                                                                                              'this '
                                                                                              'device',
                                                                               'type': 'string'},
                                                              'name': {'description': 'the '
                                                                                      'name '
                                                                                      'of '
                                                                                      'this '
                                                                                      'device',
                                                                       'type': 'string'}},
                                               'required': ['name'],
                                               'tag': 'pynwb.device.Device',
                                               'type': 'object'},
                                    'ElectrodeGroup': {'additionalProperties': False,
                                                       'properties': {'description': {'description': 'description '
                                                                                                     'of '
                                                                                                     'this '
                                                                                                     'electrode '
                                                                                                     'group',
                                                                                      'type': 'string'},
                                                                      'device': {'description': 'the '
                                                                                                'device '
                                                                                                'that '
                                                                                                'was '
                                                                                                'used '
                                                                                                'to '
                                                                                                'record '
                                                                                                'from '
                                                                                                'this '
                                                                                                'electrode '
                                                                                                'group',
                                                                                 'target': 'pynwb.device.Device',
                                                                                 'type': 'string'},
                                                                      'location': {'description': 'description '
                                                                                                  'of '
                                                                                                  'location '
                                                                                                  'of '
                                                                                                  'this '
                                                                                                  'electrode '
                                                                                                  'group',
                                                                                   'type': 'string'},
                                                                      'name': {'description': 'the '
                                                                                              'name '
                                                                                              'of '
                                                                                              'this '
                                                                                              'electrode',
                                                                               'type': 'string'}},
                                                       'required': ['description',
                                                                    'device',
                                                                    'name',
                                                                    'location'],
                                                       'tag': 'pynwb.ecephys.ElectrodeGroup',
                                                       'type': 'object'},
                                    'Electrodes': {'additionalProperties': False,
                                                   'properties': {'data': {'default': [nan],
                                                                           'description': 'values '
                                                                                          'for '
                                                                                          'each '
                                                                                          'row '
                                                                                          'in '
                                                                                          'this '
                                                                                          'electrodes '
                                                                                          'column',
                                                                           'type': 'array'},
                                                                  'description': {'description': 'description '
                                                                                                 'of '
                                                                                                 'this '
                                                                                                 'electrodes '
                                                                                                 'column',
                                                                                  'type': 'string'},
                                                                  'name': {'description': 'name '
                                                                                          'of '
                                                                                          'this '
                                                                                          'electrodes '
                                                                                          'column',
                                                                           'type': 'string'}},
                                                   'required': ['name'],
                                                   'type': 'object'}}},
     'required': ['Device', 'ElectrodeGroup'],
     'tag': 'Ecephys',
     'type': 'object'}

On instance['Ecephys']:
    {'Device': [{'description': 'Axona DacqUSB, sw_version=1.2.2.16',
                 'manufacturer': 'Axona',
                 'name': 'Axona'}],
     'ElectricalSeries': {'description': 'Raw acquisition traces.',
                          'name': 'ElectricalSeries'},
     'ElectrodeGroup': [{'description': 'Group 0 electrodes.',
                         'device': 'Axona',
                         'location': '',
                         'name': 'Group0'},
                        {'description': 'Group 1 electrodes.',
                         'device': 'Axona',
                         'location': '',
                         'name': 'Group1'},
                        {'description': 'Group 2 electrodes.',
                         'device': 'Axona',
                         'location': '',
                         'name': 'Group2'},
                        {'description': 'Group 3 electrodes.',
                         'device': 'Axona',
                         'location': '',
                         'name': 'Group3'}],
     'Electrodes': [{'data': ['Group0',
                              'Group0',
                              'Group0',
                              'Group0',
                              'Group1',
                              'Group1',
                              'Group1',
                              'Group1',
                              'Group2',
                              'Group2',
                              'Group2',
                              'Group2',
                              'Group3',
                              'Group3',
                              'Group3',
                              'Group3'],
                     'description': 'The name of the ElectrodeGroup this '
                                    'electrode\n'
                                    '                                is a '
                                    'part of.',
                     'name': 'group_name'}]}
```

**Comment by CodyCBakerPhD** [comment]
@luiztauffer `ElectricalSeries` ought to be in the metadata schema for Ecephys, right? Can you look into resolving this?

**Comment by luiztauffer** [comment]
There can be more than one ElectricalSeries-like key in metadata['Ecephys']. The `AxonaRecordingExtractorInterface` should add it to its schema as either:
- ElectricalSeries_raw
- ElectricalSeries_processed
- ElectricalSeries_lfp

**Comment by luiztauffer** [comment]
also, as per our discussion today, the electrodes data should be added as properties of the respective recordingextractor, right?

**Comment by CodyCBakerPhD** [comment]
> also, as per our discussion today, the electrodes data should be added as properties of the respective recordingextractor, right?

Channel properties, yes.

We'll probably have to make a splinter PR prior to merging Sakshams changes that goes through each interface and update that behavior.

**Comment by sbuergers** [comment]
@luiztauffer sorry for not getting back to this sooner. I was trying to wrap up the other parts of the Hussaini project. 

I am not immediately sure how to accomplish what you suggest, but I can look into it - or as @CodyCBakerPhD suggests we can make a separate PR and adjust for all interfaces there.

Why was this PR closed actually?

**Comment by CodyCBakerPhD** [comment]
@sbuergers It looks like the PR was automatically closed by the 
`
fix <link to issue or PR>
`
command from [this merge](https://github.com/catalystneuro/nwb-conversion-tools/pull/185) on `nwb-conversion-tools`. How interesting that it applies to PRs outside of it's a repository - I figured it only worked on Issues in the same location as the PR.

The changelog is pretty small though, feel free to repost another PR with the same code when it's working and we'll try again.

**Pull request closed without merging**
